### ISSUE TITLE
[serverless-cdk-plugin] unable to redeploy a stack with an event bus defined through the plugin

### ISSUE THREAD

**Issue by fargito** [swarmion/swarmion#337] opened 2022-11-03 13:43 UTC
Hello!

I have provisionned an EventBus using the `serverless-cdk-plugin`.

However, now that I want to redeploy my service, I get a CDK error:
```
Environment: linux, node 16.17.0, framework 3.23.0 (local), plugin 6.2.2, SDK 4.3.2
Credentials: Local, "swarmion-developer" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
Error:
UPDATE_FAILED: cdkEventBusF31270C5 (AWS::Events::EventBus)
Unsupported Operation
```

I suspect this is an issue with the plugin, @GuillaumeLagrange WDYT?

**Comment by GuillaumeLagrange** [comment] 2022-11-03 14:05
@fargito what's the cloudformation error associated with the event bus deploy failure ?

**Comment by GuillaumeLagrange** [comment] 2022-11-04 10:11
This appears to be linked to a cloud formation issue.

https://www.repost.aws/questions/QUrtTcjqzWTDa0CmmexF_auQ/event-bus-update-failed-unsupported-operation?sc_ichannel=ha&sc_ilang=en&sc_isite=repost&sc_iplace=hp&sc_icontent=QUrtTcjqzWTDa0CmmexF_auQ&sc_ipos=17

Response from AWS support to the OP:

>To begin with I would like to inform you that this is a known issue by our CloudFormation service team, and they are already working on a fix for this issue. The issue is caused by updating stack-level tags(not resource level tags i.e., even without specifically having made changes to the resource) on “AWS::Events::EventBus” resource type. The current workaround is to not make any changes to the stack-level tags used by any stacks containing an “AWS::Events::EventBridge“ resource. This will result in this resource not being updated thus allowing you to resume with update of your stacks without facing this error.
Also, we were able to replicate the scenario at our end. We created a stack with an "AWS::Events::EventBus" resource with Resource Level Tags and no error was shown after multiple updates requested. However, when we tried to add Stack Level Tags, we encountered the same error you are facing. Hence, it is confirmed that the issue is with the "Stack level tags".
Unfortunately, I’m not able to provide ETA on when this issue might be fixed since AWS Support Engineers are not privy to development road-maps. I would like to apologize for the inconvenience caused.
Rest assured, I will keep the case in Pending Amazon Action and I will keep you updated on the resolution of this issue as soon as I have an update from the internal Team.

Keeping an eye on it though

**Comment by fargito** [comment] 2022-11-05 08:25
Thanks for the investigation!

**Comment by GuillaumeLagrange** [comment] 2022-12-16 14:07
@fargito can we close this ?

**Comment by fargito** [comment] 2022-12-16 18:29
We can indeed!

**Closed** 2022-12-16 18:30 UTC
